version: "3.8"

services:
  minecraft:
    image: cubeddocker
    container_name: Minecraft
    ports:
      - "25565:25565"  # Expose the server port statically as it's already defined in the environment variables
    environment:
      MEMORY: "4G"
      PROXY: "false"
      MINECRAFT_VIEW_DISTANCE: "12"
      MINECRAFT_MAX_PLAYERS: "30"
      MINECRAFT_SERVER_NAME: "server1"
      MINECRAFT_MOTD: "Welcome to My Minecraft Server"
      MINECRAFT_PVP: "true"
      MINECRAFT_ENABLE_JMX_MONITORING: "false"
      MINECRAFT_RCON_PORT: "25575"
      MINECRAFT_LEVEL_SEED: ""
      MINECRAFT_GAMEMODE: "survival"
      MINECRAFT_ENABLE_COMMAND_BLOCK: "false"
      MINECRAFT_ENABLE_QUERY: "false"
      MINECRAFT_GENERATOR_SETTINGS: "{}"
      MINECRAFT_ENFORCE_SECURE_PROFILE: "true"
      MINECRAFT_LEVEL_NAME: "world"
      MINECRAFT_QUERY_PORT: "25565"
      MINECRAFT_GENERATE_STRUCTURES: "true"
      MINECRAFT_MAX_CHAINED_NEIGHBOR_UPDATES: "1000000"
      MINECRAFT_DIFFICULTY: "easy"
      MINECRAFT_NETWORK_COMPRESSION_THRESHOLD: "256"
      MINECRAFT_MAX_TICK_TIME: "60000"
      MINECRAFT_REQUIRE_RESOURCE_PACK: "false"
      MINECRAFT_USE_NATIVE_TRANSPORT: "true"
      MINECRAFT_ONLINE_MODE: "true"
      MINECRAFT_ENABLE_STATUS: "true"
      MINECRAFT_ALLOW_FLIGHT: "false"
      MINECRAFT_INITIAL_DISABLED_PACKS: ""
      MINECRAFT_BROADCAST_RCON_TO_OPS: "true"
      MINECRAFT_SERVER_IP: ""
      MINECRAFT_RESOURCE_PACK_PROMPT: ""
      MINECRAFT_ALLOW_NETHER: "true"
      MINECRAFT_SERVER_PORT: "25565"
      MINECRAFT_ENABLE_RCON: "false"
      MINECRAFT_SYNC_CHUNK_WRITES: "true"
      MINECRAFT_OP_PERMISSION_LEVEL: "4"
      MINECRAFT_PREVENT_PROXY_CONNECTIONS: "false"
      MINECRAFT_HIDE_ONLINE_PLAYERS: "false"
      MINECRAFT_RESOURCE_PACK: ""
      MINECRAFT_ENTITY_BROADCAST_RANGE_PERCENTAGE: "100"
      MINECRAFT_SIMULATION_DISTANCE: "10"
      MINECRAFT_RCON_PASSWORD: ""
      MINECRAFT_PLAYER_IDLE_TIMEOUT: "0"
      MINECRAFT_FORCE_GAMEMODE: "false"
      MINECRAFT_RATE_LIMIT: "0"
      MINECRAFT_HARDCORE: "false"
      MINECRAFT_WHITE_LIST: "false"
      MINECRAFT_BROADCAST_CONSOLE_TO_OPS: "true"
      MINECRAFT_SPAWN_NPCS: "true"
      MINECRAFT_SPAWN_ANIMALS: "true"
      MINECRAFT_LOG_IPS: "true"
      MINECRAFT_FUNCTION_PERMISSION_LEVEL: "2"
      MINECRAFT_INITIAL_ENABLED_PACKS: "vanilla"
      MINECRAFT_LEVEL_TYPE: "minecraft:normal"
      MINECRAFT_TEXT_FILTERING_CONFIG: ""
      MINECRAFT_SPAWN_MONSTERS: "true"
      MINECRAFT_ENFORCE_WHITELIST: "false"
      MINECRAFT_SPAWN_PROTECTION: "16"
      MINECRAFT_RESOURCE_PACK_SHA1: ""
      MINECRAFT_MAX_WORLD_SIZE: "29999984"
      
    volumes:
      - minecraft_servers:/minecraft/server
    restart: unless-stopped
    networks:
      - cyciorg_default

volumes:
  minecraft_servers:

networks:
  cyciorg_default:
    external: true
